config/routes.rb
Rails.application.routes.draw do
  #get 'index/top'
  #get 'bbs/top'
  root 'index#top'
  get '/bbs', to:'bbs#top', as:'bbs'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/user_new', to:'bbs#user_new', as:'user_new'
  post '/user_create', to:'bbs#user_create', as:'user_create'
  get '/user_login', to:'bbs#user_login', as: 'user_login'
  post '/user_confirm', to:'bbs#user_confirm', as:'user_confirm'
  get '/user_top', to:'bbs#user_top', as: 'user_top'
  get '/user_logout', to:'bbs#user_logout', as: 'user_logout'
  post '/post_new', to:'bbs#post_new', as:'post_new'
  get '/reply', to: 'bbs#reply', as:'reply'
  post '/comment', to:'bbs#comment', as:'comment'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user, foreign_key: :user_id	
    has_many :replies
end

app/models/reply.rb
class Reply < ApplicationRecord
    belongs_to :post, foreign_key: :post_id
    belongs_to :user, foreign_key: :user_id
end

app/models/user.rb
class User < ApplicationRecord
    has_many :posts
    has_many :replies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bbs_controller.rb
require 'date'
class BbsController < ApplicationController
  def top
    @users = User.all
  end
  def user_new
    @user = User.new
  end
  def user_create
    #time = Time.now
    @user = User.new(name: params[:name], mail: params[:mail], password: params[:pwd])
    if @user.save
      redirect_to(user_login_path)
    else
      render 'new' and return
    end
  end
  def user_login
    @post = Post.new
  end
  def user_confirm
     @user = User.find_by(mail: params[:mail], password: params[:pwd])
    if @user
      #flash[:notice] = "ログインしました"
      session[:user_id] = @user.id
      redirect_to(user_top_path)
      #puts 'ヒットしました！'
      
    else
      #puts 'いませんでした'
      render("user_login")
    end
  end
  def user_top
   @user = User.find_by_id(session[:user_id])
   #@posts = Post.all
   #@posts = Post.joins(:user)
   #@users = User.joins(:posts)
   #@users = User.joins(:posts).select('users.name as name, posts.title as title, posts.body as body')
   @posts = Post.joins(:user).select('posts.id as post_id, users.name as name, posts.title as title, posts.body as body, posts.created_at as created_at')
  end
  def user_logout
    session[:user_id] = nil
    redirect_to(user_login_path)
  end
  
  def post_new
     @post = Post.new(user_id: session[:user_id], title: params[:title], body: params[:body])
    if @post.save
      redirect_to(user_top_path)
    else
      render 'post_new' and return
    end
  end
  def reply
    @post_id = params[:post_id]
    @posts = Post.joins(:user).select('posts.id as post_id, users.name as name, posts.title as title, posts.body as body').where('posts.id = ?', @post_id)
    @comment = Reply.new
    @replies = Reply.joins(:post).joins(:user).select('posts.id as post_id, users.name as name, replies.content as content').where('post_id=?', @post_id)
    #@user = User.find_by(id: session[:user_id])
  end
  def comment
    @content = params[:content]
    @post_id = params[:post_id]
    #puts @post_id
    #puts @content
    
    @reply = Reply.new(post_id: @post_id, user_id: session[:user_id], content: @content)
    
    if @reply.save
      redirect_to(user_top_path)
    else
      render 'new' and return
    end
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bbs_helper.rb
module BbsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/views/bbs/comment.html.erb
aa

app/views/bbs/reply.html.erb
<h1>投稿への返信</h1>

<table>
    <tr>
        <th>投稿ID</th>
        <th>投稿者</th>
        <th>タイトル</th>
        <th>内容</th>
    </tr>
    <% @posts.each do |post| %>
    <tr>
        <td><%= post.post_id %></td>
        <td><%= post.name %></td>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
    </tr>
    <tr>
        <td colspan="4">
            <% @replies.each do |reply| %>
            <div class="wrap">
                <div><%= reply.name %></div>
                <div><%= reply.content %></div>
            </div>
            
             <% end %>
        </td>
        </tr>
        <tr>
        <td colspan="4">
            <%= form_tag("/comment") do %>  
            <div class="text-wrap">
            返信<input type="text" name="content" placeholder="返信内容" value="">
            </div>
            <%= hidden_field_tag :post_id, post.post_id %>
            <input type="submit" value="返信">
             <% end %>
        </td>
    </tr>
    <% end %>
</table>
<%= link_to 'ユーザトップへ' , user_top_path %>

app/views/bbs/top.html.erb
<h1>登録ユーザ一覧</h1>
<ul>
    <% @users.each do |user| %>
        <li>ID:<%= user.id %> / 名前:<%= user.name %> / mail: <%= user.mail %> / password: <%= user.password %> / 作成日時: <%= user.created_at %></li>
    <% end %>
</ul>

<div><%= link_to 'システムトップへ', root_path %></div>

app/views/bbs/user_login.html.erb
<h1>ログイン</h1>
<div class="new-tweet">
     <%= form_tag("/user_confirm") do %>  
        <div class="text-wrap">
            メールアドレス<input type="text" name="mail" placeholder="メールアドレス" value="">
        </div>
        <div class="text-wrap">
            パスワード<input type="text" name="pwd" placeholder="パスワード" value="">
        </div>
        <input type="submit" value="送信">
    <% end %>
</div>
<div><%= link_to 'システムトップへ', root_path %></div>

app/views/bbs/user_new.html.erb
<h1>ログイン・新規ユーザ登録</h1>


<div>
<h2>ログイン</h2>    
    <%= link_to 'ログインフォームへ', user_login_path %>
    
</div>

<h2>アカウントをお持ちでない方は新規作成ください</h2>
<div class="new-tweet">
     <%= form_tag("/user_create") do %>  
        <div class="text-wrap">
            
            ユーザ名<input type="text" name="name" placeholder="ユーザ名" value="">
        </div>
        <div class="text-wrap">
            メールアドレス<input type="text" name="mail" placeholder="メールアドレス" value="">
        </div>
        <div class="text-wrap">
            パスワード<input type="text" name="pwd" placeholder="パスワード" value="">
        </div>
        <input type="submit" value="登録">
    <% end %>
</div>

<div><%= link_to 'システムトップへ', root_path %></div>

app/views/bbs/user_top.html.erb
<%= @user.name %>さん、ようこそ！


<h1>投稿一覧</h1>
<table>
    <tr>
        <th>ユーザ名</th>
        <th>タイトル </th>
        <th>内容</th>
        <th>日時</th>
        <th>返信する</th>
    </tr>
    <% @posts.each do |post| %>
    <tr>
         <td><%= post.post_id %></td>
        <td><%= post.name %></td>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= post.created_at %></td>
        <td><%= link_to "返信", reply_path(post, post_id: post.post_id) %></td>
    </tr>
    <% end %>
</table>

<h1>新規投稿</h1>

<div class="new-tweet">
     
     <%= form_tag("/post_new") do %>  
        <div class="text-wrap">
            タイトル<input type="text" name="title" placeholder="タイトル" value="">
        </div>
        <div class="text-wrap">
            投稿内容<input type="text" name="body" placeholder="投稿内容" value="">
        </div>
        
        <input type="submit" value="投稿">
    <% end %>
</div>

<div><%= link_to 'ログアウト', user_logout_path %></div>

app/views/index/top.html.erb
<h1>掲示板システム</h1>

<div><%= link_to '管理者ページへ', bbs_path %></div>
<div><%= link_to '利用者ページへ', user_new_path %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TableJoin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>